//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Abarroteria.DataBase
{
    using System;
    using System.Collections.Generic;
    
    public partial class Inventario
    {
        public int InventarioId { get; set; }
        public int BodegaId { get; set; }
        public int ProductoId { get; set; }
        public int Disponible { get; set; }
    
        public virtual Bodega Bodega { get; set; }
        public virtual Producto Productos { get; set; }
    }
}
