//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Abarroteria.DataBase
{
    using System;
    using System.Collections.Generic;
    
    public partial class PrecioVenta
    {
        public int PrecioVentaID { get; set; }
        public int ProductoID { get; set; }
        public decimal Precio { get; set; }
        public System.DateTime FechaDesde { get; set; }
        public System.DateTime FechaHasta { get; set; }
        public int ListaPrecio { get; set; }
    
        public virtual ListaPrecio ListaPrecio1 { get; set; }
        public virtual Producto Productos { get; set; }
    }
}
